export const brands = [
  {
    name: 'Northwind Audio',
    slug: 'northwind-audio',
    description: 'Acoustic engineers building headphones and speakers tuned for natural, fatigue-free listening.',
    website: 'https://northwindaudio.example.com',
    isFeatured: true,
  },
  {
    name: 'Maison Verre',
    slug: 'maison-verre',
    description: 'A modern perfume house blending French perfumery with Indian botanicals. Every fragrance is aged for six weeks before bottling.',
    website: 'https://maisonverre.example.com',
    isFeatured: true,
  },
  {
    name: 'Stride Athletics',
    slug: 'stride-athletics',
    description: 'Performance footwear and training gear designed with runners from Bengaluru to Leh.',
    website: 'https://strideathletics.example.com',
    isFeatured: true,
  },
  {
    name: 'Kora Living',
    slug: 'kora-living',
    description: 'Handcrafted decor and kitchenware made in collaboration with artisan clusters across India.',
    website: 'https://koraliving.example.com',
    isFeatured: false,
  },
  {
    name: 'Luma Beauty',
    slug: 'luma-beauty',
    description: 'Clean, dermatologist-tested skincare and makeup formulated for Indian skin and climate.',
    website: 'https://lumabeauty.example.com',
    isFeatured: true,
  },
  {
    name: 'Atlas Leather',
    slug: 'atlas-leather',
    description: 'Full-grain leather goods cut and stitched by hand in Kanpur, built to age beautifully.',
    website: 'https://atlasleather.example.com',
    isFeatured: false,
  },
  {
    name: 'Everloom',
    slug: 'everloom',
    description: 'Wardrobe essentials in GOTS-certified organic cotton and linen. Fewer, better clothes.',
    website: 'https://everloom.example.com',
    isFeatured: true,
  },
  {
    name: 'Pulse Tech',
    slug: 'pulse-tech',
    description: 'Smart wearables and charging accessories that just work, backed by a nationwide service network.',
    website: 'https://pulsetech.example.com',
    isFeatured: false,
  },
  {
    name: 'Terra Outdoor',
    slug: 'terra-outdoor',
    description: 'Rugged bags, jackets and eyewear for commuters and weekend explorers.',
    website: 'https://terraoutdoor.example.com',
    isFeatured: false,
  },
  {
    name: 'Solace Home',
    slug: 'solace-home',
    description: 'Luxury bedding and bath linen woven from long-staple cotton for restful nights.',
    website: 'https://solacehome.example.com',
    isFeatured: false,
  },
  {
    name: 'Indigo Loom',
    slug: 'indigo-loom',
    description: 'Contemporary ethnic wear celebrating hand-block prints and handloom weaves from Rajasthan and Bengal.',
    website: 'https://indigoloom.example.com',
    isFeatured: false,
  },
];
