export const categories = [
  {
    name: 'Men',
    slug: 'men',
    description: 'Considered essentials for men: organic cotton tees, crisp shirts and outerwear built to last.',
    sortOrder: 1,
    image: { url: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=800&q=80', alt: 'Man in a tailored outfit' },
    seo: {
      title: 'Men’s Clothing | BlueMart',
      description: 'Shop premium men’s t-shirts, shirts and jackets at BlueMart. Free shipping across India on orders above ₹999.',
    },
    children: [
      {
        name: 'T-Shirts',
        slug: 'men-t-shirts',
        description: 'Everyday tees in organic cotton and supima blends.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80', alt: 'Plain white t-shirt' },
      },
      {
        name: 'Shirts',
        slug: 'men-shirts',
        description: 'Oxford, linen and poplin shirts for work and weekends.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80', alt: 'Button-down shirt' },
      },
      {
        name: 'Jackets',
        slug: 'men-jackets',
        description: 'Leather, bomber and overshirt jackets for cooler days.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80', alt: 'Black leather jacket' },
      },
    ],
  },
  {
    name: 'Women',
    slug: 'women',
    description: 'Modern silhouettes and handcrafted ethnic wear for women.',
    sortOrder: 2,
    image: { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80', alt: 'Woman carrying shopping bags' },
    seo: {
      title: 'Women’s Clothing | BlueMart',
      description: 'Discover premium dresses, tops and ethnic wear for women at BlueMart. Easy 15-day returns.',
    },
    children: [
      {
        name: 'Dresses',
        slug: 'women-dresses',
        description: 'Midi, maxi and wrap dresses in breathable fabrics.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80', alt: 'Floral summer dress' },
      },
      {
        name: 'Tops',
        slug: 'women-tops',
        description: 'Blouses, knit tops and tees for every day.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=800&q=80', alt: 'Woman wearing a casual top' },
      },
      {
        name: 'Ethnic Wear',
        slug: 'women-ethnic-wear',
        description: 'Handloom kurtas, sarees and festive sets.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80', alt: 'Woman in a silk saree' },
      },
    ],
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    description: 'Sneakers, performance runners and formal shoes crafted for comfort.',
    sortOrder: 3,
    image: { url: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80', alt: 'Pair of shoes' },
    seo: {
      title: 'Premium Footwear | BlueMart',
      description: 'Shop sneakers, running shoes and formal footwear from leading brands at BlueMart.',
    },
    children: [
      {
        name: 'Sneakers',
        slug: 'footwear-sneakers',
        description: 'Clean everyday sneakers in leather and knit.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80', alt: 'Pair of sneakers' },
      },
      {
        name: 'Running Shoes',
        slug: 'footwear-running',
        description: 'Cushioned, responsive shoes for road and track.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80', alt: 'Running shoe' },
      },
      {
        name: 'Formal Shoes',
        slug: 'footwear-formal',
        description: 'Oxfords, derbies and loafers in full-grain leather.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80', alt: 'Leather formal shoes' },
      },
    ],
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Audio, wearables and accessories engineered for everyday life.',
    sortOrder: 4,
    image: { url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=800&q=80', alt: 'Electronic devices on a desk' },
    seo: {
      title: 'Electronics & Gadgets | BlueMart',
      description: 'Headphones, smartwatches and tech accessories with brand warranty. Shop electronics at BlueMart.',
    },
    children: [
      {
        name: 'Audio',
        slug: 'electronics-audio',
        description: 'Headphones, earbuds and portable speakers.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80', alt: 'Wireless headphones' },
      },
      {
        name: 'Wearables',
        slug: 'electronics-wearables',
        description: 'Smartwatches and fitness bands.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80', alt: 'Smartwatch' },
      },
      {
        name: 'Tech Accessories',
        slug: 'electronics-accessories',
        description: 'Chargers, power banks, keyboards and more.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80', alt: 'Mechanical keyboard' },
      },
    ],
  },
  {
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Decor, kitchenware and bedding that make a house feel like home.',
    sortOrder: 5,
    image: { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80', alt: 'Styled living room' },
    seo: {
      title: 'Home & Living | BlueMart',
      description: 'Shop lamps, vases, cookware and luxury bedding. Thoughtfully designed homeware at BlueMart.',
    },
    children: [
      {
        name: 'Decor',
        slug: 'home-decor',
        description: 'Lamps, vases, candles and accents.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=800&q=80', alt: 'Ceramic vase' },
      },
      {
        name: 'Kitchen & Dining',
        slug: 'home-kitchen',
        description: 'Cookware, mugs and serveware.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80', alt: 'Modern kitchen' },
      },
      {
        name: 'Bedding',
        slug: 'home-bedding',
        description: 'Bedsheets, duvets and throws.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80', alt: 'Neatly made bed' },
      },
    ],
  },
  {
    name: 'Beauty',
    slug: 'beauty',
    description: 'Clean skincare, fine fragrance and makeup.',
    sortOrder: 6,
    image: { url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80', alt: 'Beauty products on a table' },
    seo: {
      title: 'Beauty & Fragrance | BlueMart',
      description: 'Shop serums, perfumes and makeup from premium beauty brands. 100% authentic products at BlueMart.',
    },
    children: [
      {
        name: 'Skincare',
        slug: 'beauty-skincare',
        description: 'Serums, moisturisers and cleansers.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80', alt: 'Skincare bottles' },
      },
      {
        name: 'Fragrance',
        slug: 'beauty-fragrance',
        description: 'Eau de parfum and eau de toilette.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80', alt: 'Perfume bottle' },
      },
      {
        name: 'Makeup',
        slug: 'beauty-makeup',
        description: 'Lipsticks, palettes and complexion.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80', alt: 'Makeup products' },
      },
    ],
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Watches, sunglasses and leather goods to finish every look.',
    sortOrder: 7,
    image: { url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80', alt: 'Analog wristwatch' },
    seo: {
      title: 'Watches & Accessories | BlueMart',
      description: 'Shop watches, sunglasses and leather wallets. Premium accessories with free shipping at BlueMart.',
    },
    children: [
      {
        name: 'Watches',
        slug: 'accessories-watches',
        description: 'Automatic and quartz timepieces.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80', alt: 'Minimal watch' },
      },
      {
        name: 'Sunglasses',
        slug: 'accessories-sunglasses',
        description: 'Polarised and UV400 eyewear.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80', alt: 'Sunglasses' },
      },
      {
        name: 'Wallets',
        slug: 'accessories-wallets',
        description: 'Bifolds, cardholders and zip wallets.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80', alt: 'Leather wallet' },
      },
    ],
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Yoga, training and gym equipment for every routine.',
    sortOrder: 8,
    image: { url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80', alt: 'Person training in a gym' },
    seo: {
      title: 'Sports & Fitness Gear | BlueMart',
      description: 'Yoga mats, dumbbells and training essentials for home and gym workouts. Shop at BlueMart.',
    },
    children: [
      {
        name: 'Yoga',
        slug: 'sports-yoga',
        description: 'Mats, blocks and straps.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80', alt: 'Woman practising yoga' },
      },
      {
        name: 'Gym Equipment',
        slug: 'sports-gym-equipment',
        description: 'Dumbbells, bands and bottles.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80', alt: 'Dumbbells on a rack' },
      },
    ],
  },
  {
    name: 'Bags',
    slug: 'bags',
    description: 'Backpacks, handbags and luggage for work and travel.',
    sortOrder: 9,
    image: { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80', alt: 'Backpack' },
    seo: {
      title: 'Bags, Backpacks & Luggage | BlueMart',
      description: 'Shop laptop backpacks, leather handbags and cabin luggage from premium brands at BlueMart.',
    },
    children: [
      {
        name: 'Backpacks',
        slug: 'bags-backpacks',
        description: 'Laptop and everyday backpacks.',
        sortOrder: 1,
        image: { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80', alt: 'Backpack outdoors' },
      },
      {
        name: 'Handbags',
        slug: 'bags-handbags',
        description: 'Totes, satchels and crossbody bags.',
        sortOrder: 2,
        image: { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80', alt: 'Leather handbag' },
      },
      {
        name: 'Travel',
        slug: 'bags-travel',
        description: 'Cabin trolleys, duffels and organisers.',
        sortOrder: 3,
        image: { url: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=800&q=80', alt: 'Travel luggage' },
      },
    ],
  },
];
