export default [
  {
    name: 'Luma Beauty 15% Vitamin C Brightening Serum',
    slug: 'luma-beauty-15-vitamin-c-brightening-serum',
    sku: 'LMA-VITC-SERUM',
    category: 'beauty',
    subcategory: 'beauty-skincare',
    brand: 'luma-beauty',
    shortDescription: 'A stable 15% ethyl ascorbic acid serum with ferulic acid and niacinamide to fade dark spots and boost glow.',
    description:
      'Formulated for humid Indian weather, this lightweight serum absorbs in seconds without stickiness. It uses 15% ethyl ascorbic acid, a stable form of vitamin C that does not oxidise as quickly as L-ascorbic acid, paired with ferulic acid and vitamin E to boost antioxidant protection.\n\n' +
      '4% niacinamide helps even out tone and refine pores, while hyaluronic acid adds a boost of hydration. In an 8-week consumer study, 87% of users reported visibly brighter skin.\n\n' +
      'Apply 3–4 drops each morning after cleansing and follow with sunscreen. Packed in an airless amber pump to protect the formula.',
    price: 899,
    compareAtPrice: 1199,
    taxRate: 18,
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80', alt: 'Luma Beauty vitamin C serum' },
      { url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80', alt: 'Serum dropper bottle' },
    ],
    attributes: [
      { name: 'Volume', value: '30 ml' },
      { name: 'Key Ingredients', value: '15% ethyl ascorbic acid, 4% niacinamide, ferulic acid, vitamin E' },
      { name: 'Skin Type', value: 'All skin types, including sensitive' },
      { name: 'Free From', value: 'Fragrance, parabens, sulphates' },
      { name: 'Shelf Life', value: '24 months; use within 6 months of opening' },
    ],
    tags: ['vitamin c', 'serum', 'skincare', 'brightening'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    returnPolicy: 'Returns accepted only for sealed, unused products within 7 days.',
    seo: {
      title: '15% Vitamin C Brightening Serum | Luma Beauty',
      description: 'Luma Beauty 15% vitamin C serum with niacinamide and ferulic acid. Fades dark spots for brighter skin.',
      keywords: ['vitamin c serum', 'face serum', 'brightening serum', 'luma beauty'],
    },
    stock: 58,
  },
  {
    name: 'Luma Beauty Ceramide Barrier Repair Moisturiser',
    slug: 'luma-beauty-ceramide-barrier-repair-moisturiser',
    sku: 'LMA-CERAMIDE-MOIST',
    category: 'beauty',
    subcategory: 'beauty-skincare',
    brand: 'luma-beauty',
    shortDescription: 'A gel-cream moisturiser with five ceramides and panthenol that restores the skin barrier without feeling heavy.',
    description:
      'Pollution, harsh actives and air-conditioning can all weaken your skin barrier. This gel-cream replenishes it with a skin-identical blend of five ceramides, cholesterol and fatty acids.\n\n' +
      'Panthenol and centella soothe redness, and the non-comedogenic texture suits oily and combination skin. Use morning and night as the last step before sunscreen.',
    price: 749,
    compareAtPrice: 849,
    taxRate: 18,
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80', alt: 'Luma Beauty ceramide moisturiser' },
      { url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=80', alt: 'Skincare products flat lay' },
    ],
    attributes: [
      { name: 'Volume', value: '50 g' },
      { name: 'Key Ingredients', value: '5 ceramides, panthenol, centella asiatica' },
      { name: 'Texture', value: 'Lightweight gel-cream' },
      { name: 'Skin Type', value: 'Oily, combination, sensitive' },
      { name: 'Free From', value: 'Fragrance, alcohol, parabens' },
    ],
    tags: ['moisturiser', 'ceramides', 'skin barrier', 'skincare'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    returnPolicy: 'Returns accepted only for sealed, unused products within 7 days.',
    seo: {
      title: 'Ceramide Barrier Repair Moisturiser | Luma',
      description: 'Lightweight gel-cream moisturiser with five ceramides and panthenol to repair the skin barrier.',
      keywords: ['ceramide moisturiser', 'gel moisturiser', 'oily skin moisturiser', 'luma beauty'],
    },
    stock: 47,
  },
  {
    name: 'Luma Beauty Velvet Matte Lipstick',
    slug: 'luma-beauty-velvet-matte-lipstick',
    sku: 'LMA-VELVET-LIP',
    category: 'beauty',
    subcategory: 'beauty-makeup',
    brand: 'luma-beauty',
    shortDescription: 'A richly pigmented, transfer-resistant matte lipstick enriched with shea butter so lips never feel dry.',
    description:
      'Velvet Matte delivers full, one-swipe colour with a soft-focus finish that lasts up to 10 hours. Unlike traditional mattes, it is enriched with shea butter and vitamin E to keep lips comfortable all day.\n\n' +
      'Shades were developed and tested on a wide range of Indian skin tones, from fair to deep. Vegan and cruelty-free.',
    price: 699,
    compareAtPrice: 899,
    taxRate: 18,
    images: [
      { url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80', alt: 'Luma Beauty velvet matte lipstick' },
      { url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=80', alt: 'Makeup collection with lipsticks' },
    ],
    attributes: [
      { name: 'Net Weight', value: '4.2 g' },
      { name: 'Finish', value: 'Velvet matte' },
      { name: 'Wear Time', value: 'Up to 10 hours' },
      { name: 'Key Ingredients', value: 'Shea butter, vitamin E' },
      { name: 'Certification', value: 'Vegan, cruelty-free' },
    ],
    tags: ['lipstick', 'matte', 'makeup', 'vegan'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    returnPolicy: 'Returns accepted only for sealed, unused products within 7 days.',
    seo: {
      title: 'Velvet Matte Long-Wear Lipstick | Luma Beauty',
      description: 'Luma Beauty transfer-resistant velvet matte lipstick with shea butter. Shades for Indian skin tones.',
      keywords: ['matte lipstick', 'long lasting lipstick', 'vegan lipstick', 'luma beauty'],
    },
    variants: [
      { sku: 'LMA-VELVET-LIP-RUBY', color: 'Ruby Rush', colorHex: '#9b111e', price: 699, compareAtPrice: 899, stock: 40 },
      { sku: 'LMA-VELVET-LIP-NUDE', color: 'Chai Nude', colorHex: '#a47551', price: 699, compareAtPrice: 899, stock: 52 },
      { sku: 'LMA-VELVET-LIP-MAUV', color: 'Mauve Muse', colorHex: '#915f6d', price: 699, compareAtPrice: 899, stock: 33 },
    ],
  },
  {
    name: 'Maison Verre Eau de Parfum – Santal Noir',
    slug: 'maison-verre-eau-de-parfum-santal-noir',
    sku: 'MSV-EDP-SANTAL',
    category: 'beauty',
    subcategory: 'beauty-fragrance',
    brand: 'maison-verre',
    shortDescription: 'A smoky, creamy woody fragrance built around Mysore sandalwood, black pepper and oud. Long-lasting eau de parfum.',
    description:
      'Santal Noir opens with a spark of black pepper and pink peppercorn before settling into a heart of creamy Mysore sandalwood and iris. The dry-down is dark and enveloping, with oud, leather and a touch of vanilla.\n\n' +
      'Concentrated at 20% perfume oil, it lasts 8–10 hours on skin and even longer on fabric. The fragrance is aged for six weeks before being bottled in our signature weighted glass flacon.\n\n' +
      'A unisex scent that is equally at home at an evening wedding or a quiet dinner.',
    price: 6499,
    compareAtPrice: 7999,
    taxRate: 18,
    images: [
      { url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80', alt: 'Maison Verre Santal Noir eau de parfum' },
      { url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80', alt: 'Perfume bottle on a marble surface' },
    ],
    attributes: [
      { name: 'Concentration', value: 'Eau de parfum, 20% perfume oil' },
      { name: 'Top Notes', value: 'Black pepper, pink peppercorn' },
      { name: 'Heart Notes', value: 'Mysore sandalwood, iris' },
      { name: 'Base Notes', value: 'Oud, leather, vanilla' },
      { name: 'Longevity', value: '8–10 hours' },
      { name: 'Gender', value: 'Unisex' },
    ],
    tags: ['perfume', 'eau de parfum', 'sandalwood', 'unisex', 'luxury'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    shippingInfo: 'Free shipping in a gift-ready box.',
    returnPolicy: 'Returns accepted only for sealed, unused products within 7 days.',
    seo: {
      title: 'Santal Noir Eau de Parfum | Maison Verre',
      description: 'Maison Verre Santal Noir eau de parfum with Mysore sandalwood, oud and black pepper. Long-lasting.',
      keywords: ['sandalwood perfume', 'eau de parfum', 'unisex perfume', 'luxury perfume', 'maison verre'],
    },
    variants: [
      { sku: 'MSV-EDP-SANTAL-50', size: '50 ml', price: 6499, compareAtPrice: 7999, stock: 30 },
      { sku: 'MSV-EDP-SANTAL-100', size: '100 ml', price: 9999, compareAtPrice: 12499, stock: 16 },
    ],
  },
  {
    name: 'Maison Verre Eau de Parfum – Jasmin Mogra',
    slug: 'maison-verre-eau-de-parfum-jasmin-mogra',
    sku: 'MSV-EDP-MOGRA',
    category: 'beauty',
    subcategory: 'beauty-fragrance',
    brand: 'maison-verre',
    shortDescription: 'A luminous white floral celebrating Indian mogra, tuberose and neroli over a soft musk base.',
    description:
      'Inspired by strings of fresh mogra sold at temple gates at dusk, Jasmin Mogra captures the flower’s heady, honeyed sweetness with a modern, airy twist.\n\n' +
      'Sparkling neroli and bergamot lead into a heart of jasmine sambac absolute and tuberose, resting on clean white musk and sandalwood. Radiant and feminine, it is perfect for daytime celebrations.',
    price: 5999,
    compareAtPrice: 6999,
    taxRate: 18,
    images: [
      { url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80', alt: 'Maison Verre Jasmin Mogra eau de parfum' },
      { url: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80', alt: 'Floral perfume bottle' },
    ],
    attributes: [
      { name: 'Concentration', value: 'Eau de parfum, 18% perfume oil' },
      { name: 'Top Notes', value: 'Neroli, bergamot' },
      { name: 'Heart Notes', value: 'Jasmine sambac, tuberose' },
      { name: 'Base Notes', value: 'White musk, sandalwood' },
      { name: 'Longevity', value: '6–8 hours' },
    ],
    tags: ['perfume', 'floral', 'jasmine', 'women'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    returnPolicy: 'Returns accepted only for sealed, unused products within 7 days.',
    seo: {
      title: 'Jasmin Mogra Eau de Parfum | Maison Verre',
      description: 'Maison Verre Jasmin Mogra eau de parfum: a luminous white floral with mogra, tuberose and neroli.',
      keywords: ['jasmine perfume', 'mogra perfume', 'floral perfume women', 'maison verre'],
    },
    variants: [
      { sku: 'MSV-EDP-MOGRA-50', size: '50 ml', price: 5999, compareAtPrice: 6999, stock: 24 },
      { sku: 'MSV-EDP-MOGRA-100', size: '100 ml', price: 8999, compareAtPrice: 10499, stock: 11 },
    ],
  },
];
