export default [
  {
    name: 'Everloom Organic Cotton Crew Tee',
    slug: 'everloom-organic-cotton-crew-tee',
    sku: 'EVL-CRW-TEE',
    category: 'men',
    subcategory: 'men-t-shirts',
    brand: 'everloom',
    shortDescription: 'A heavyweight 220 GSM crew-neck tee in GOTS-certified organic cotton with a structured, true-to-size fit.',
    description:
      'The tee we wish we had found years ago. Knitted from long-staple, GOTS-certified organic cotton grown in Madhya Pradesh, the 220 GSM single jersey has a dense, substantial hand-feel that drapes cleanly and never turns see-through.\n\n' +
      'A ribbed neckband with a taped back seam holds its shape wash after wash, while the side-seamed body and slightly dropped shoulder give a relaxed but tidy silhouette. Every piece is enzyme-washed and pre-shrunk, so the fit you try on is the fit you keep.\n\n' +
      'Dyed with low-impact, AZO-free dyes in a solar-powered facility in Tiruppur. Wear it on its own, under an overshirt or beneath a blazer.',
    price: 1299,
    compareAtPrice: 1699,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80', alt: 'Everloom organic cotton crew tee in white' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=80', alt: 'Everloom crew tee colour options' },
    ],
    attributes: [
      { name: 'Material', value: '100% GOTS-certified organic cotton, 220 GSM' },
      { name: 'Fit', value: 'Regular fit, true to size' },
      { name: 'Neckline', value: 'Ribbed crew neck' },
      { name: 'Care', value: 'Machine wash cold, inside out. Do not tumble dry.' },
      { name: 'Origin', value: 'Made in India' },
    ],
    tags: ['organic cotton', 't-shirt', 'essentials', 'crew neck'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    shippingInfo: 'Free shipping on orders above ₹999. Dispatched within 24 hours.',
    returnPolicy: 'Easy 15-day returns and exchanges on unworn items with tags intact.',
    seo: {
      title: 'Organic Cotton Crew Tee | Everloom',
      description: 'Shop the Everloom heavyweight organic cotton crew neck t-shirt. 220 GSM, pre-shrunk, made in India.',
      keywords: ['organic cotton t-shirt', 'crew neck tee', 'men t-shirt', 'everloom'],
    },
    variants: [
      { sku: 'EVL-CRW-TEE-S-WHT', size: 'S', color: 'Chalk White', colorHex: '#f5f5f0', price: 1299, compareAtPrice: 1699, stock: 24 },
      { sku: 'EVL-CRW-TEE-M-WHT', size: 'M', color: 'Chalk White', colorHex: '#f5f5f0', price: 1299, compareAtPrice: 1699, stock: 40 },
      { sku: 'EVL-CRW-TEE-L-WHT', size: 'L', color: 'Chalk White', colorHex: '#f5f5f0', price: 1299, compareAtPrice: 1699, stock: 36 },
      { sku: 'EVL-CRW-TEE-XL-WHT', size: 'XL', color: 'Chalk White', colorHex: '#f5f5f0', price: 1399, compareAtPrice: 1799, stock: 18 },
      { sku: 'EVL-CRW-TEE-S-BLK', size: 'S', color: 'Jet Black', colorHex: '#111827', price: 1299, compareAtPrice: 1699, stock: 20 },
      { sku: 'EVL-CRW-TEE-M-BLK', size: 'M', color: 'Jet Black', colorHex: '#111827', price: 1299, compareAtPrice: 1699, stock: 45 },
      { sku: 'EVL-CRW-TEE-L-BLK', size: 'L', color: 'Jet Black', colorHex: '#111827', price: 1299, compareAtPrice: 1699, stock: 0 },
      { sku: 'EVL-CRW-TEE-XL-BLK', size: 'XL', color: 'Jet Black', colorHex: '#111827', price: 1399, compareAtPrice: 1799, stock: 12 },
      { sku: 'EVL-CRW-TEE-S-OLV', size: 'S', color: 'Olive', colorHex: '#556b2f', price: 1299, compareAtPrice: 1699, stock: 10 },
      { sku: 'EVL-CRW-TEE-M-OLV', size: 'M', color: 'Olive', colorHex: '#556b2f', price: 1299, compareAtPrice: 1699, stock: 22 },
      { sku: 'EVL-CRW-TEE-L-OLV', size: 'L', color: 'Olive', colorHex: '#556b2f', price: 1299, compareAtPrice: 1699, stock: 19 },
      { sku: 'EVL-CRW-TEE-XL-OLV', size: 'XL', color: 'Olive', colorHex: '#556b2f', price: 1399, compareAtPrice: 1799, stock: 8 },
    ],
  },
  {
    name: 'Stride Athletics DryPace Training Tee',
    slug: 'stride-athletics-drypace-training-tee',
    sku: 'STR-DRYPACE-TEE',
    category: 'men',
    subcategory: 'men-t-shirts',
    brand: 'stride-athletics',
    shortDescription: 'Lightweight, quick-dry training tee with laser-cut ventilation zones and anti-odour finish for high-sweat sessions.',
    description:
      'Built for Indian summers and indoor HIIT alike, the DryPace tee uses a recycled polyester micro-mesh that pulls sweat away from the skin and dries in minutes. Laser-perforated panels across the upper back dump heat where you need it most.\n\n' +
      'Flatlock seams eliminate chafing on long runs, and a silver-ion anti-odour treatment keeps the tee fresh between washes. Reflective logo hits add visibility for early-morning and late-evening workouts.\n\n' +
      'The athletic cut sits close without clinging, leaving plenty of room for full range of motion during lifts, sprints and mobility work.',
    price: 899,
    compareAtPrice: 1299,
    taxRate: 5,
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=80', alt: 'Stride DryPace training tee' },
      { url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=1200&q=80', alt: 'Training tee worn during a workout' },
    ],
    attributes: [
      { name: 'Material', value: '88% recycled polyester, 12% elastane micro-mesh' },
      { name: 'Fit', value: 'Athletic fit' },
      { name: 'Technology', value: 'Quick-dry, anti-odour silver-ion finish, UPF 30' },
      { name: 'Care', value: 'Machine wash cold. Do not use fabric softener.' },
      { name: 'Origin', value: 'Made in India' },
    ],
    tags: ['activewear', 'training', 'quick dry', 'gym tee'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    shippingInfo: 'Free shipping on orders above ₹999.',
    returnPolicy: '15-day returns on unworn items.',
    seo: {
      title: 'DryPace Quick-Dry Training Tee | Stride',
      description: 'Stride Athletics DryPace training t-shirt with quick-dry mesh, anti-odour finish and flatlock seams.',
      keywords: ['gym t-shirt', 'dri fit tee', 'training tee', 'stride athletics'],
    },
    variants: [
      { sku: 'STR-DRYPACE-TEE-S-GRY', size: 'S', color: 'Graphite', colorHex: '#374151', price: 899, compareAtPrice: 1299, stock: 30 },
      { sku: 'STR-DRYPACE-TEE-M-GRY', size: 'M', color: 'Graphite', colorHex: '#374151', price: 899, compareAtPrice: 1299, stock: 42 },
      { sku: 'STR-DRYPACE-TEE-L-GRY', size: 'L', color: 'Graphite', colorHex: '#374151', price: 899, compareAtPrice: 1299, stock: 38 },
      { sku: 'STR-DRYPACE-TEE-XL-GRY', size: 'XL', color: 'Graphite', colorHex: '#374151', price: 899, compareAtPrice: 1299, stock: 15 },
      { sku: 'STR-DRYPACE-TEE-S-BLU', size: 'S', color: 'Cobalt Blue', colorHex: '#1d4ed8', price: 899, compareAtPrice: 1299, stock: 14 },
      { sku: 'STR-DRYPACE-TEE-M-BLU', size: 'M', color: 'Cobalt Blue', colorHex: '#1d4ed8', price: 899, compareAtPrice: 1299, stock: 27 },
      { sku: 'STR-DRYPACE-TEE-L-BLU', size: 'L', color: 'Cobalt Blue', colorHex: '#1d4ed8', price: 899, compareAtPrice: 1299, stock: 21 },
      { sku: 'STR-DRYPACE-TEE-XL-BLU', size: 'XL', color: 'Cobalt Blue', colorHex: '#1d4ed8', price: 899, compareAtPrice: 1299, stock: 2 },
    ],
  },
  {
    name: 'Everloom Classic Oxford Button-Down Shirt',
    slug: 'everloom-classic-oxford-button-down-shirt',
    sku: 'EVL-OXF-SHIRT',
    category: 'men',
    subcategory: 'men-shirts',
    brand: 'everloom',
    shortDescription: 'A timeless Oxford cloth shirt with a soft-roll button-down collar, box pleat and curved hem. Office-ready, weekend-approved.',
    description:
      'Woven from two-ply organic cotton Oxford cloth, this shirt has the textured basketweave and gentle sheen that only gets better with wear. The unlined button-down collar has a natural roll that looks equally sharp with or without a tie.\n\n' +
      'Details are borrowed from the best Ivy-league classics: a back box pleat and locker loop, a single chest pocket, genuine mother-of-pearl buttons and single-needle stitching at 16 stitches per inch.\n\n' +
      'The tailored fit is trim through the body without being tight, and the curved hem is cut to be worn tucked or untucked.',
    price: 2499,
    compareAtPrice: 3299,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80', alt: 'Everloom Oxford button-down shirt' },
      { url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80', alt: 'Oxford shirt worn with trousers' },
    ],
    attributes: [
      { name: 'Material', value: '100% organic cotton two-ply Oxford' },
      { name: 'Fit', value: 'Tailored fit' },
      { name: 'Collar', value: 'Button-down' },
      { name: 'Buttons', value: 'Mother-of-pearl' },
      { name: 'Care', value: 'Machine wash warm. Warm iron.' },
      { name: 'Origin', value: 'Made in India' },
    ],
    tags: ['oxford shirt', 'formal', 'workwear', 'organic cotton'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    shippingInfo: 'Free shipping on orders above ₹999.',
    returnPolicy: 'Easy 15-day returns and exchanges.',
    seo: {
      title: 'Classic Oxford Button-Down Shirt | Everloom',
      description: 'Shop the Everloom organic cotton Oxford shirt with button-down collar and mother-of-pearl buttons.',
      keywords: ['oxford shirt', 'men formal shirt', 'button down shirt', 'everloom'],
    },
    variants: [
      { sku: 'EVL-OXF-SHIRT-S-BLU', size: 'S', color: 'Sky Blue', colorHex: '#93c5fd', price: 2499, compareAtPrice: 3299, stock: 16 },
      { sku: 'EVL-OXF-SHIRT-M-BLU', size: 'M', color: 'Sky Blue', colorHex: '#93c5fd', price: 2499, compareAtPrice: 3299, stock: 28 },
      { sku: 'EVL-OXF-SHIRT-L-BLU', size: 'L', color: 'Sky Blue', colorHex: '#93c5fd', price: 2499, compareAtPrice: 3299, stock: 25 },
      { sku: 'EVL-OXF-SHIRT-XL-BLU', size: 'XL', color: 'Sky Blue', colorHex: '#93c5fd', price: 2599, compareAtPrice: 3399, stock: 11 },
      { sku: 'EVL-OXF-SHIRT-S-WHT', size: 'S', color: 'White', colorHex: '#ffffff', price: 2499, compareAtPrice: 3299, stock: 18 },
      { sku: 'EVL-OXF-SHIRT-M-WHT', size: 'M', color: 'White', colorHex: '#ffffff', price: 2499, compareAtPrice: 3299, stock: 30 },
      { sku: 'EVL-OXF-SHIRT-L-WHT', size: 'L', color: 'White', colorHex: '#ffffff', price: 2499, compareAtPrice: 3299, stock: 26 },
      { sku: 'EVL-OXF-SHIRT-XL-WHT', size: 'XL', color: 'White', colorHex: '#ffffff', price: 2599, compareAtPrice: 3399, stock: 9 },
    ],
  },
  {
    name: 'Everloom Pure Linen Resort Shirt',
    slug: 'everloom-pure-linen-resort-shirt',
    sku: 'EVL-LIN-RESORT',
    category: 'men',
    subcategory: 'men-shirts',
    brand: 'everloom',
    shortDescription: 'Breathable European flax linen shirt with a relaxed camp collar, made for humid afternoons and beachside evenings.',
    description:
      'Cut from 100% European flax linen, garment-washed for a lived-in softness from day one. Linen’s natural hollow fibres wick moisture and keep air moving, which makes this the shirt to reach for when the mercury climbs past 35°C.\n\n' +
      'The open camp collar, straight hem and boxy, slightly cropped body are designed to be worn untucked over shorts or chinos. Coconut-shell buttons add a warm, natural finish.\n\n' +
      'Expect the characteristic slubs and creases that make linen what it is — they are part of the charm.',
    price: 2799,
    compareAtPrice: 3499,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1200&q=80', alt: 'Everloom linen resort shirt' },
      { url: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=1200&q=80', alt: 'Linen shirt detail' },
    ],
    attributes: [
      { name: 'Material', value: '100% European flax linen, 150 GSM' },
      { name: 'Fit', value: 'Relaxed fit' },
      { name: 'Collar', value: 'Camp (Cuban) collar' },
      { name: 'Care', value: 'Machine wash cold, line dry. Iron while damp.' },
      { name: 'Origin', value: 'Made in India' },
    ],
    tags: ['linen', 'summer', 'resort wear', 'camp collar'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    shippingInfo: 'Free shipping on orders above ₹999.',
    returnPolicy: 'Easy 15-day returns and exchanges.',
    seo: {
      title: 'Pure Linen Resort Shirt | Everloom',
      description: 'Relaxed-fit European flax linen shirt with camp collar. Breathable summer shirt by Everloom.',
      keywords: ['linen shirt', 'men summer shirt', 'camp collar shirt', 'resort shirt'],
    },
    variants: [
      { sku: 'EVL-LIN-RESORT-S-SND', size: 'S', color: 'Sand', colorHex: '#d6c7a1', price: 2799, compareAtPrice: 3499, stock: 12 },
      { sku: 'EVL-LIN-RESORT-M-SND', size: 'M', color: 'Sand', colorHex: '#d6c7a1', price: 2799, compareAtPrice: 3499, stock: 20 },
      { sku: 'EVL-LIN-RESORT-L-SND', size: 'L', color: 'Sand', colorHex: '#d6c7a1', price: 2799, compareAtPrice: 3499, stock: 17 },
      { sku: 'EVL-LIN-RESORT-XL-SND', size: 'XL', color: 'Sand', colorHex: '#d6c7a1', price: 2799, compareAtPrice: 3499, stock: 7 },
      { sku: 'EVL-LIN-RESORT-S-SGE', size: 'S', color: 'Sage Green', colorHex: '#9caf88', price: 2799, compareAtPrice: 3499, stock: 9 },
      { sku: 'EVL-LIN-RESORT-M-SGE', size: 'M', color: 'Sage Green', colorHex: '#9caf88', price: 2799, compareAtPrice: 3499, stock: 15 },
      { sku: 'EVL-LIN-RESORT-L-SGE', size: 'L', color: 'Sage Green', colorHex: '#9caf88', price: 2799, compareAtPrice: 3499, stock: 14 },
      { sku: 'EVL-LIN-RESORT-XL-SGE', size: 'XL', color: 'Sage Green', colorHex: '#9caf88', price: 2799, compareAtPrice: 3499, stock: 6 },
    ],
  },
  {
    name: 'Atlas Leather Café Racer Jacket',
    slug: 'atlas-leather-cafe-racer-jacket',
    sku: 'ATL-CAFE-RACER',
    category: 'men',
    subcategory: 'men-jackets',
    brand: 'atlas-leather',
    shortDescription: 'A minimalist café racer in vegetable-tanned lambskin with a snap-tab collar and YKK Excella zips.',
    description:
      'Our signature jacket is cut from supple, full-grain lambskin that has been vegetable-tanned for 30 days in Kanpur. The leather arrives soft and lightweight, then gradually moulds to your shoulders and elbows to become unmistakably yours.\n\n' +
      'The café racer silhouette keeps things clean: a low snap-tab collar, asymmetric-free centre zip, two zippered hand pockets and one interior phone pocket. Hardware is YKK Excella in antique brass, and the body is lined in breathable cupro.\n\n' +
      'Each jacket takes a single artisan roughly 14 hours to cut, stitch and finish, and ships with a care kit and a dust bag.',
    price: 18999,
    compareAtPrice: 24999,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=80', alt: 'Atlas Leather café racer jacket in black' },
      { url: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=1200&q=80', alt: 'Man wearing a leather jacket' },
    ],
    attributes: [
      { name: 'Material', value: 'Full-grain vegetable-tanned lambskin, 0.9 mm' },
      { name: 'Lining', value: '100% cupro' },
      { name: 'Hardware', value: 'YKK Excella antique brass zips' },
      { name: 'Fit', value: 'Slim fit; size up for layering' },
      { name: 'Care', value: 'Professional leather clean only. Condition every 6 months.' },
      { name: 'Warranty', value: '2-year craftsmanship warranty' },
    ],
    tags: ['leather jacket', 'outerwear', 'handcrafted', 'lambskin'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    shippingInfo: 'Free insured shipping. Dispatched within 2–3 business days.',
    returnPolicy: '10-day returns on unworn jackets with tags attached.',
    seo: {
      title: 'Café Racer Leather Jacket | Atlas Leather',
      description: 'Handcrafted full-grain lambskin café racer jacket with YKK Excella zips and cupro lining.',
      keywords: ['leather jacket', 'cafe racer jacket', 'lambskin jacket', 'men jacket'],
    },
    variants: [
      { sku: 'ATL-CAFE-RACER-S-BLK', size: 'S', color: 'Black', colorHex: '#0b0b0b', price: 18999, compareAtPrice: 24999, stock: 5 },
      { sku: 'ATL-CAFE-RACER-M-BLK', size: 'M', color: 'Black', colorHex: '#0b0b0b', price: 18999, compareAtPrice: 24999, stock: 8 },
      { sku: 'ATL-CAFE-RACER-L-BLK', size: 'L', color: 'Black', colorHex: '#0b0b0b', price: 18999, compareAtPrice: 24999, stock: 7 },
      { sku: 'ATL-CAFE-RACER-XL-BLK', size: 'XL', color: 'Black', colorHex: '#0b0b0b', price: 19499, compareAtPrice: 25499, stock: 3 },
      { sku: 'ATL-CAFE-RACER-S-BRN', size: 'S', color: 'Cognac', colorHex: '#8b4513', price: 18999, compareAtPrice: 24999, stock: 4 },
      { sku: 'ATL-CAFE-RACER-M-BRN', size: 'M', color: 'Cognac', colorHex: '#8b4513', price: 18999, compareAtPrice: 24999, stock: 6 },
      { sku: 'ATL-CAFE-RACER-L-BRN', size: 'L', color: 'Cognac', colorHex: '#8b4513', price: 18999, compareAtPrice: 24999, stock: 5 },
      { sku: 'ATL-CAFE-RACER-XL-BRN', size: 'XL', color: 'Cognac', colorHex: '#8b4513', price: 19499, compareAtPrice: 25499, stock: 2 },
    ],
  },
  {
    name: 'Terra Outdoor Packable Windcheater Jacket',
    slug: 'terra-outdoor-packable-windcheater-jacket',
    sku: 'TRO-WIND-JKT',
    category: 'men',
    subcategory: 'men-jackets',
    brand: 'terra-outdoor',
    shortDescription: 'Ultralight, water-repellent windcheater that packs into its own chest pocket. Built for monsoon commutes and hill treks.',
    description:
      'Weighing just 180 grams, the Terra windcheater is made from a ripstop recycled nylon with a PFC-free DWR finish that sheds light rain and blocks gusty wind. It packs down into its own chest pocket, small enough to live permanently in your backpack.\n\n' +
      'An adjustable hood with a laminated brim, elasticated cuffs and a drawcord hem seal out the weather, while a mesh-lined back yoke lets heat escape on steep climbs.\n\n' +
      'Reflective piping on the shoulders and back keeps you visible on dark evening rides.',
    price: 3499,
    compareAtPrice: 4299,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=80', alt: 'Terra Outdoor packable windcheater' },
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=1200&q=80', alt: 'Windcheater jacket worn outdoors' },
    ],
    attributes: [
      { name: 'Material', value: '100% recycled nylon ripstop, 20D' },
      { name: 'Water Resistance', value: 'PFC-free DWR finish, 5,000 mm hydrostatic head' },
      { name: 'Weight', value: '180 g (size M)' },
      { name: 'Fit', value: 'Regular fit' },
      { name: 'Care', value: 'Machine wash cold. Tumble dry low to reactivate DWR.' },
    ],
    tags: ['windcheater', 'rain jacket', 'packable', 'outdoor'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    shippingInfo: 'Free shipping on orders above ₹999.',
    returnPolicy: 'Easy 15-day returns and exchanges.',
    seo: {
      title: 'Packable Windcheater Jacket | Terra Outdoor',
      description: 'Ultralight, water-repellent packable windcheater with adjustable hood. Ideal for monsoon and treks.',
      keywords: ['windcheater', 'rain jacket men', 'packable jacket', 'terra outdoor'],
    },
    variants: [
      { sku: 'TRO-WIND-JKT-M-NVY', size: 'M', color: 'Navy', colorHex: '#1e3a5f', price: 3499, compareAtPrice: 4299, stock: 22 },
      { sku: 'TRO-WIND-JKT-L-NVY', size: 'L', color: 'Navy', colorHex: '#1e3a5f', price: 3499, compareAtPrice: 4299, stock: 19 },
      { sku: 'TRO-WIND-JKT-XL-NVY', size: 'XL', color: 'Navy', colorHex: '#1e3a5f', price: 3499, compareAtPrice: 4299, stock: 10 },
      { sku: 'TRO-WIND-JKT-M-ORG', size: 'M', color: 'Ember Orange', colorHex: '#ea580c', price: 3499, compareAtPrice: 4299, stock: 13 },
      { sku: 'TRO-WIND-JKT-L-ORG', size: 'L', color: 'Ember Orange', colorHex: '#ea580c', price: 3499, compareAtPrice: 4299, stock: 11 },
      { sku: 'TRO-WIND-JKT-XL-ORG', size: 'XL', color: 'Ember Orange', colorHex: '#ea580c', price: 3499, compareAtPrice: 4299, stock: 6 },
    ],
  },
];
