export default [
  {
    name: 'Terra Outdoor Commuter 28L Laptop Backpack',
    slug: 'terra-outdoor-commuter-28l-laptop-backpack',
    sku: 'TRO-COMMUTER-28L',
    category: 'bags',
    subcategory: 'bags-backpacks',
    brand: 'terra-outdoor',
    shortDescription: 'A weatherproof 28 L backpack with a padded 16" laptop sleeve, clamshell opening and hidden anti-theft pocket.',
    description:
      'Built for the daily metro-to-office grind, the Commuter opens flat like a suitcase so you can pack and find things quickly. A suspended, padded sleeve protects laptops up to 16 inches from drops, and a separate tablet pocket sits right beside it.\n\n' +
      'The shell is made from 900D recycled polyester with a TPU coating and water-resistant zips, so a surprise monsoon shower will not soak your gear. A hidden back-panel pocket keeps your wallet and passport out of reach of pickpockets.\n\n' +
      'Breathable air-mesh shoulder straps, a sternum strap and a luggage pass-through make it equally good for weekend getaways.',
    price: 4999,
    compareAtPrice: 6999,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80', alt: 'Terra Outdoor Commuter laptop backpack' },
      { url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=1200&q=80', alt: 'Backpack carried outdoors' },
    ],
    attributes: [
      { name: 'Capacity', value: '28 litres' },
      { name: 'Laptop Compartment', value: 'Fits up to 16" laptops, suspended and padded' },
      { name: 'Material', value: '900D recycled polyester with TPU coating' },
      { name: 'Dimensions', value: '48 x 31 x 18 cm' },
      { name: 'Weight', value: '1.2 kg' },
      { name: 'Warranty', value: '3-year warranty' },
    ],
    tags: ['laptop backpack', 'water resistant', 'commute', 'anti theft'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    shippingInfo: 'Free shipping. Delivered in 3–5 business days.',
    returnPolicy: '15-day returns on unused products with tags.',
    seo: {
      title: 'Commuter 28L Laptop Backpack | Terra Outdoor',
      description: 'Weatherproof 28 L laptop backpack with 16" sleeve, clamshell opening and anti-theft pocket.',
      keywords: ['laptop backpack', 'office backpack', 'waterproof backpack', 'terra outdoor'],
    },
    variants: [
      { sku: 'TRO-COMMUTER-28L-BLK', color: 'Black', colorHex: '#111827', price: 4999, compareAtPrice: 6999, stock: 38 },
      { sku: 'TRO-COMMUTER-28L-OLV', color: 'Olive', colorHex: '#4d5d3a', price: 4999, compareAtPrice: 6999, stock: 17 },
    ],
  },
  {
    name: 'Terra Outdoor Rolltop Waterproof Backpack 22L',
    slug: 'terra-outdoor-rolltop-waterproof-backpack-22l',
    sku: 'TRO-ROLLTOP-22L',
    category: 'bags',
    subcategory: 'bags-backpacks',
    brand: 'terra-outdoor',
    shortDescription: 'A fully waterproof roll-top backpack with welded seams, built for cyclists, bikers and monsoon adventurers.',
    description:
      'The Rolltop keeps everything bone-dry, whether you are riding through a downpour or hopping on a ferry. Radio-frequency welded seams and a triple-fold roll closure create a truly waterproof seal.\n\n' +
      'An expandable roll-top lets you stretch capacity from 22 to 26 litres, and a padded laptop sleeve fits 15-inch devices. Reflective accents and a light loop keep you visible after dark.',
    price: 3799,
    compareAtPrice: 4499,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&w=1200&q=80', alt: 'Terra Outdoor rolltop waterproof backpack' },
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80', alt: 'Backpack detail' },
    ],
    attributes: [
      { name: 'Capacity', value: '22–26 litres (expandable)' },
      { name: 'Material', value: '500D PVC-free tarpaulin, RF-welded seams' },
      { name: 'Waterproofing', value: 'IPX6, roll-top closure' },
      { name: 'Laptop Compartment', value: 'Fits up to 15"' },
      { name: 'Warranty', value: '2-year warranty' },
    ],
    tags: ['waterproof backpack', 'rolltop', 'cycling', 'monsoon'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    returnPolicy: '15-day returns on unused products with tags.',
    seo: {
      title: 'Rolltop Waterproof Backpack 22L | Terra',
      description: 'Terra Outdoor fully waterproof 22 L roll-top backpack with welded seams and 15" laptop sleeve.',
      keywords: ['waterproof backpack', 'rolltop backpack', 'biker backpack', 'monsoon bag'],
    },
    stock: 26,
  },
  {
    name: 'Atlas Leather Structured Everyday Tote',
    slug: 'atlas-leather-structured-everyday-tote',
    sku: 'ATL-STRUCT-TOTE',
    category: 'bags',
    subcategory: 'bags-handbags',
    brand: 'atlas-leather',
    shortDescription: 'A roomy, structured tote in pebbled leather that fits a 14" laptop, with a zip pocket and detachable pouch.',
    description:
      'The tote that goes from boardroom to weekend brunch. Cut from pebbled full-grain leather, it holds its shape beautifully while resisting scratches and scuffs.\n\n' +
      'Inside, a suede-lined laptop slip fits most 14-inch devices, and a detachable zip pouch keeps small essentials organised. Sturdy handles with a 23 cm drop sit comfortably on the shoulder, and brass feet protect the base.\n\n' +
      'Each tote is finished by hand in our Kanpur atelier, with painted edges and a debossed Atlas mark.',
    price: 11999,
    compareAtPrice: 14999,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=80', alt: 'Atlas Leather structured tote' },
      { url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80', alt: 'Leather tote bag styled' },
    ],
    attributes: [
      { name: 'Material', value: 'Pebbled full-grain leather, suede lining' },
      { name: 'Dimensions', value: '38 x 29 x 14 cm' },
      { name: 'Handle Drop', value: '23 cm' },
      { name: 'Laptop Fit', value: 'Up to 14"' },
      { name: 'Included', value: 'Detachable zip pouch, dust bag' },
      { name: 'Warranty', value: '1-year craftsmanship warranty' },
    ],
    tags: ['tote bag', 'leather handbag', 'work bag', 'women'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    shippingInfo: 'Free insured shipping with dust bag.',
    returnPolicy: '15-day returns on unused products with tags.',
    seo: {
      title: 'Structured Leather Everyday Tote | Atlas',
      description: 'Atlas Leather pebbled full-grain leather tote with 14" laptop slip and detachable pouch.',
      keywords: ['leather tote bag', 'women handbag', 'laptop tote', 'atlas leather'],
    },
    variants: [
      { sku: 'ATL-STRUCT-TOTE-BLK', color: 'Black', colorHex: '#0a0a0a', price: 11999, compareAtPrice: 14999, stock: 12 },
      { sku: 'ATL-STRUCT-TOTE-TAN', color: 'Caramel', colorHex: '#b5763a', price: 11999, compareAtPrice: 14999, stock: 9 },
      { sku: 'ATL-STRUCT-TOTE-BRG', color: 'Burgundy', colorHex: '#6d1a36', price: 12499, compareAtPrice: 15499, stock: 1 },
    ],
  },
  {
    name: 'Atlas Leather Mini Crossbody Satchel',
    slug: 'atlas-leather-mini-crossbody-satchel',
    sku: 'ATL-MINI-SATCHEL',
    category: 'bags',
    subcategory: 'bags-handbags',
    brand: 'atlas-leather',
    shortDescription: 'A compact saddle-leather satchel with an adjustable strap and turn-lock closure, sized for phone, keys and cards.',
    description:
      'Hands-free and effortlessly elegant, this mini satchel is made from smooth saddle leather that develops a rich patina over time. A polished brass turn-lock keeps the flap secure.\n\n' +
      'The adjustable, detachable strap can be worn crossbody or on the shoulder. Inside, there is room for a large smartphone, keys, lipstick and a slim card holder.',
    price: 5999,
    compareAtPrice: 7499,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80', alt: 'Atlas Leather mini crossbody satchel' },
      { url: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=1200&q=80', alt: 'Crossbody bag detail' },
    ],
    attributes: [
      { name: 'Material', value: 'Smooth saddle leather, cotton twill lining' },
      { name: 'Dimensions', value: '21 x 16 x 7 cm' },
      { name: 'Strap', value: 'Adjustable, detachable, max drop 60 cm' },
      { name: 'Closure', value: 'Brass turn-lock' },
    ],
    tags: ['crossbody bag', 'satchel', 'leather', 'mini bag'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    returnPolicy: '15-day returns on unused products with tags.',
    seo: {
      title: 'Mini Leather Crossbody Satchel | Atlas',
      description: 'Compact saddle leather crossbody satchel with brass turn-lock and adjustable strap by Atlas Leather.',
      keywords: ['crossbody bag', 'leather sling bag', 'mini satchel', 'women bag'],
    },
    stock: 21,
  },
  {
    name: 'Terra Outdoor Voyager 55cm Cabin Trolley',
    slug: 'terra-outdoor-voyager-55cm-cabin-trolley',
    sku: 'TRO-VOYAGER-55',
    category: 'bags',
    subcategory: 'bags-travel',
    brand: 'terra-outdoor',
    shortDescription: 'A lightweight polycarbonate cabin suitcase with 360° silent spinner wheels, TSA lock and a front laptop pocket.',
    description:
      'Voyager fits the cabin-size limits of all major Indian airlines, so you can skip the baggage belt. Its 100% virgin polycarbonate shell flexes on impact and bounces back, and a textured finish hides scuffs.\n\n' +
      'Japanese Hinomoto double-spinner wheels glide silently across airport floors, and a multi-stage aluminium handle locks at three heights. A zippered front pocket gives quick access to a 15-inch laptop at security.\n\n' +
      'Inside, compression straps and a zipped divider keep clothes neat, and an integrated TSA-approved lock secures the main compartment.',
    price: 8999,
    compareAtPrice: 12999,
    taxRate: 12,
    images: [
      { url: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=1200&q=80', alt: 'Terra Outdoor Voyager cabin trolley' },
      { url: 'https://images.unsplash.com/photo-1553531384-cc64ac80f931?auto=format&fit=crop&w=1200&q=80', alt: 'Traveller with luggage at the airport' },
    ],
    attributes: [
      { name: 'Material', value: '100% virgin polycarbonate shell' },
      { name: 'Dimensions', value: '55 x 38 x 22 cm (cabin size)' },
      { name: 'Capacity', value: '40 litres' },
      { name: 'Weight', value: '2.6 kg' },
      { name: 'Wheels', value: 'Hinomoto 360° double spinner' },
      { name: 'Lock', value: 'Integrated TSA-approved combination lock' },
      { name: 'Warranty', value: '5-year international warranty' },
    ],
    tags: ['cabin luggage', 'trolley bag', 'travel', 'suitcase'],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    shippingInfo: 'Free shipping. Delivered in 3–6 business days.',
    returnPolicy: '15-day returns on unused luggage with tags.',
    seo: {
      title: 'Voyager 55cm Cabin Trolley | Terra Outdoor',
      description: 'Lightweight polycarbonate 55 cm cabin trolley with spinner wheels, TSA lock and laptop pocket.',
      keywords: ['cabin trolley', 'cabin luggage', 'suitcase', 'polycarbonate trolley'],
    },
    variants: [
      { sku: 'TRO-VOYAGER-55-GRY', color: 'Slate Grey', colorHex: '#64748b', price: 8999, compareAtPrice: 12999, stock: 16 },
      { sku: 'TRO-VOYAGER-55-NVY', color: 'Deep Navy', colorHex: '#1e293b', price: 8999, compareAtPrice: 12999, stock: 14 },
      { sku: 'TRO-VOYAGER-55-SGE', color: 'Sage', colorHex: '#87a987', price: 9499, compareAtPrice: 12999, stock: 0 },
    ],
  },
];
